/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#dabebe",
        "surface-container-highest": "#353437",
        "on-tertiary-fixed-variant": "#564242",
        primary: "#d8bfd6",
        "secondary-container": "#5f3e3e",
        "surface-container-high": "#2a2a2c",
        "surface-container-lowest": "#0e0e10",
        "primary-fixed-dim": "#d8bfd6",
        outline: "#978e95",
        "inverse-primary": "#6c586c",
        "error-container": "#93000a",
        "outline-variant": "#4c454a",
        "on-secondary": "#462828",
        "inverse-on-surface": "#313032",
        background: "#131315",
        "on-error": "#690005",
        "on-secondary-fixed": "#2e1414",
        "on-primary-fixed-variant": "#534153",
        tertiary: "#dcc0c0",
        "surface-tint": "#d8bfd6",
        "on-tertiary-fixed": "#271718",
        "on-surface": "#e5e1e4",
        "secondary-fixed": "#ffdad9",
        "on-background": "#e5e1e4",
        "surface-container": "#201f21",
        "on-surface-variant": "#cec4ca",
        "surface-container-low": "#1c1b1d",
        "secondary-fixed-dim": "#e9bbbb",
        error: "#ffb4ab",
        surface: "#131315",
        "primary-container": "#5e4b5e",
        "surface-variant": "#353437",
        "tertiary-fixed": "#f9dcdb",
        "on-primary-container": "#d6bdd3",
        secondary: "#e9bbbb",
        "tertiary-container": "#614c4c",
        "inverse-surface": "#e5e1e4",
        "on-secondary-container": "#d7aaaa",
        "on-primary": "#3c2b3c",
        "on-secondary-fixed-variant": "#5f3e3e",
        "on-primary-fixed": "#251627",
        "surface-bright": "#39393b",
        "primary-fixed": "#f5dbf2",
        "on-error-container": "#ffdad6",
        "tertiary-fixed-dim": "#dcc0c0",
        "surface-dim": "#131315",
        "on-tertiary": "#3e2c2c",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "0.01em", fontWeight: "300" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "400" }],
        display: ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "300" }],
      },
      keyframes: {
        "pulse-slow": {
          "0%, 100%": { opacity: "0.4", transform: "scale(1)" },
          "50%": { opacity: "0.7", transform: "scale(1.05)" },
        },
        "fade-in": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        "voice-user-in": {
          "0%": { opacity: "0", transform: "translateY(6px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "voice-ai-in": {
          "0%": { opacity: "0", transform: "translateY(8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "pulse-slow": "pulse-slow 8s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "fade-in": "fade-in 0.4s ease-out",
        "voice-user-in": "voice-user-in 1.5s ease-out both",
        "voice-ai-in": "voice-ai-in 0.7s ease-out both",
      },
    },
  },
  plugins: [],
};
